services:
  chaps-db:
    image: postgres:18-alpine
    container_name: ukps_chaps_db
    environment:
      POSTGRES_USER: chaps_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: chaps_ledger
    ports:
      - "5420:5432"
    volumes:
      - ./chaps-service/internal/db:/docker-entrypoint-initdb.d:ro
      - chaps_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chaps_admin -d chaps_ledger"]
      interval: 5s
      timeout: 5s
      retries: 10

  chaps-app:
    build: ./chaps-service
    container_name: ukps_chaps_server
    platform: linux/amd64
    ports:
      - "8420:8080"
    environment:
      DATABASE_URL: "postgres://chaps_admin:password123@chaps-db:5432/chaps_ledger"
    depends_on:
      chaps-db:
        condition: service_healthy
    networks:
      - default
      - chaps_klik

  fps-db:
    image: postgres:18-alpine
    container_name: ukps_fps_db
    environment:
      POSTGRES_USER: fps_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fps_ledger
    ports:
      - "5421:5432"
    volumes:
      - ./fps-service/internal/db:/docker-entrypoint-initdb.d:ro
      - fps_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fps_admin -d fps_ledger"]
      interval: 5s
      timeout: 5s
      retries: 10

  fps-app:
    build: ./fps-service
    container_name: ukps_fps_server
    platform: linux/amd64
    ports:
      - "8421:8081"
      - "7421:7421"
    environment:
      DATABASE_URL: "postgres://fps_admin:password123@fps-db:5432/fps_ledger"
      ISO8583_PORT: ":7421"
    depends_on:
      fps-db:
        condition: service_healthy

  bacs-db:
    image: postgres:18-alpine
    container_name: ukps_bacs_db
    environment:
      POSTGRES_USER: bacs_admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bacs_ledger
    ports:
      - "5422:5432"
    volumes:
      - ./bacs-service/internal/db:/docker-entrypoint-initdb.d:ro
      - bacs_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bacs_admin -d bacs_ledger"]
      interval: 5s
      timeout: 5s
      retries: 10

  bacs-app:
    build: ./bacs-service
    container_name: ukps_bacs_server
    platform: linux/amd64
    ports:
      - "8422:8082"
    environment:
      DATABASE_URL: "postgres://bacs_admin:password123@bacs-db:5432/bacs_ledger"
    depends_on:
      bacs-db:
        condition: service_healthy

  # central-bank-app:
  #   build: ./central-bank-service
  #   container_name: central_bank_server
  #   platform: linux/amd64
  #   ports:
  #     - "8090:8090"
  #   environment:
  #     CHAPS_URL: "http://chaps-app:8080"
  #     FPS_URL: "http://fps-app:8081"
  #     BACS_URL: "http://bacs-app:8082"
  #   depends_on:
  #     - chaps-app
  #     - fps-app
  #     - bacs-app

networks:
  chaps_klik:
    name: chaps_klik

volumes:
  chaps_data:
  fps_data:
  bacs_data:
