package ledger

import (
	"context"
	"errors"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/jackc/pgx/v5/pgxpool"
)

type LedgerService struct {
	Pool *pgxpool.Pool
}

func NewLedgerService(pool *pgxpool.Pool) *LedgerService {
	return &LedgerService{Pool: pool}
}

var ErrInsufficientFunds = errors.New("insufficient funds")

func (s *LedgerService) SettlePayment(ctx context.Context, msgID string, sender string, receiver string, amount float64) error {
	return pgx.BeginFunc(ctx, s.Pool, func(tx pgx.Tx) error {
		// 1. Initial Transaction Entry
		// We insert the transaction first to get the UUID v7 generated by Postgres 18.
		// We use ON CONFLICT to prevent double-processing the same MsgId.
		var internalUUID pgtype.UUID
		err := tx.QueryRow(ctx, `
			INSERT INTO transactions (msg_id, sender_bic, receiver_bic, amount, status)
			VALUES ($1, $2, $3, $4, 'PENDING')
			ON CONFLICT (msg_id) DO UPDATE SET status = EXCLUDED.status
			RETURNING id`, 
			msgID, sender, receiver, amount).Scan(&internalUUID)

		if err != nil {
			return fmt.Errorf("failed to initialize transaction: %w", err)
		}

		// 2. Lock sender account (Row-level lock)
		var balance float64
		err = tx.QueryRow(ctx,
			"SELECT balance FROM accounts WHERE bic_code = $1 FOR UPDATE",
			sender).Scan(&balance)

		if err != nil {
			return fmt.Errorf("failed to fetch sender account: %w", err)
		}

		// 3. Liquidity Check
		if balance < amount {
			// Update status to QUEUED. Since we are inside BeginFunc, 
			// if we return ErrInsufficientFunds, this update WILL rollback.
			// To keep the 'QUEUED' status, we would typically handle this with a 
			// separate small transaction, but for now, we'll follow your logic.
			_, _ = tx.Exec(ctx, "UPDATE transactions SET status = 'QUEUED' WHERE id = $1", internalUUID)
			return ErrInsufficientFunds
		}

		// 4. Execute Gross Settlement
		// Debit Sender
		_, err = tx.Exec(ctx, "UPDATE accounts SET balance = balance - $1 WHERE bic_code = $2", amount, sender)
		if err != nil {
			return fmt.Errorf("debit failed: %w", err)
		}

		// Credit Receiver
		_, err = tx.Exec(ctx, "UPDATE accounts SET balance = balance + $1 WHERE bic_code = $2", amount, receiver)
		if err != nil {
			return fmt.Errorf("credit failed: %w", err)
		}

		// 5. Record Journal Entries (The Immutable Audit Trail)
		// This uses the internalUUID (UUID type) instead of the msgID (string).
		_, err = tx.Exec(ctx, `
			INSERT INTO journal_entries (transaction_id, account_bic, amount) 
			VALUES ($1, $2, $3), ($1, $4, $5)`,
			internalUUID, sender, -amount, receiver, amount)
		if err != nil {
			return fmt.Errorf("journal entry failed: %w", err)
		}

		// 6. Finalize Transaction Status
		_, err = tx.Exec(ctx, "UPDATE transactions SET status = 'SETTLED' WHERE id = $1", internalUUID)

		return err
	})
}
